//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Busard.SqlServer.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Busard.SqlServer.Resources.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT 
        ///	g.group_id,
        ///	g.name,
        ///	g.failure_condition_level,
        ///	g.health_check_timeout,
        ///	g.automated_backup_preference_desc as [automated_backup_preference],
        ///	gs.primary_recovery_health as [primary_health],
        ///	gs.primary_replica,
        ///	gs.secondary_recovery_health as [secondary_health],
        ///	gs.synchronization_health as [synchronization_health]
        ///FROM sys.availability_groups g
        ///JOIN sys.dm_hadr_availability_group_states gs ON g.group_id = gs.group_id.
        /// </summary>
        internal static string GetAvailabilityGroups {
            get {
                return ResourceManager.GetString("GetAvailabilityGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT name
        ///	                              ,database_id
        ///	                              ,compatibility_level
        ///	                              ,collation_name
        ///	                              ,is_read_only
        ///	                              ,is_auto_close_on
        ///	                              ,is_auto_shrink_on
        ///	                              ,state_desc
        ///	                              ,recovery_model_desc
        ///	                              ,is_auto_create_stats_on
        ///	                              ,is_auto_update_stats [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string GetDatabasesList {
            get {
                return ResourceManager.GetString("GetDatabasesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT 
        ///	c.cluster_name,
        ///	c.quorum_type,
        ///	c.quorum_state
        ///FROM sys.dm_hadr_cluster c.
        /// </summary>
        internal static string GetDmHadrCluster {
            get {
                return ResourceManager.GetString("GetDmHadrCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT 
        ///	cm.member_name,
        ///	cm.member_type,
        ///	cm.member_state,
        ///	cm.number_of_quorum_votes
        ///FROM sys.dm_hadr_cluster_members cm;.
        /// </summary>
        internal static string GetHadrClusterMembers {
            get {
                return ResourceManager.GetString("GetHadrClusterMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT 
        ///	cn.group_name
        ///   ,cn.replica_server_name
        ///   ,cn.node_name,
        ///	cs.join_state as join_state
        ///FROM sys.dm_hadr_availability_replica_cluster_nodes cn
        ///JOIN sys.dm_hadr_availability_replica_cluster_states cs ON cn.replica_server_name = cs.replica_server_name
        ///ORDER BY cn.group_name;.
        /// </summary>
        internal static string GetHadrClusterNodes {
            get {
                return ResourceManager.GetString("GetHadrClusterNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT 
        ///	g.name as AG,
        ///	ar.replica_server_name,
        ///	ar.availability_mode_desc as [availability_mode],
        ///	ar.failover_mode_desc as [failover_mode],
        ///	ar.session_timeout,
        ///	ar.primary_role_allow_connections_desc as [primary_role_allow_connections],
        ///	ar.secondary_role_allow_connections_desc as [secondary_role_allow_connections]
        ///FROM sys.availability_replicas ar
        ///JOIN sys.availability_groups g ON ar.group_id = g.group_id
        ///ORDER BY g.name, ar.replica_server_name;.
        /// </summary>
        internal static string GetHadrReplica {
            get {
                return ResourceManager.GetString("GetHadrReplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT
        ///                SERVERPROPERTY(&apos;MachineName&apos;) AS ComputerName,
        ///                SERVERPROPERTY(&apos;ServerName&apos;) AS InstanceName,
        ///                SERVERPROPERTY(&apos;Edition&apos;) AS Edition,
        ///                SERVERPROPERTY(&apos;ProductVersion&apos;) AS ProductVersion,
        ///                SERVERPROPERTY(&apos;ProductLevel&apos;) AS ProductLevel;.
        /// </summary>
        internal static string GetServerMetadata {
            get {
                return ResourceManager.GetString("GetServerMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EXEC master.dbo.xp_readerrorlog 0, 1, NULL, NULL, &apos;{0}&apos; , NULL, N&apos;asc&apos;, NULL.
        /// </summary>
        internal static string GetXpReadErrorlog {
            get {
                return ResourceManager.GetString("GetXpReadErrorlog", resourceCulture);
            }
        }
    }
}
